<a href="https://colab.research.google.com/github/sjlippe/MAT-421/blob/main/MAT421_HomeworkD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Homework Module D: 1.1, 1.2, 1.3**

# 1.1 Basics of Linear Algebra

Naturals (ℕ)

ℕ={1,2,3,4,⋯}

Wholes (𝕎)

𝕎=ℕ∪{0}

Integers (ℤ)

ℤ=𝕎∪{−1,−2,−3,⋯}

Rationals (ℚ)

ℚ={𝑝𝑞:𝑝∈ℤ,𝑞∈ℤ∖{0}}

Irrationals (𝕀)

𝕀 - the set of real numbers not expressible as a fraction of integers.

Reals (ℝ)

ℝ=ℚ∪𝕀

Complex Numbers (ℂ)

ℂ={𝑎+𝑏𝑖:𝑎,𝑏∈ℝ,𝑖=−1‾‾‾√}

# 1.2 Elements of Linear Algebra
Linear Subspace - (of V) is a subset U ⊆ V that is closed under vector addition and scalar multiplication. That is for all u1, u2 ∊ U and a ∊ R it holds u1 + u2 and a u1 ∊ u.

Span - let w1,...,wm ∊ V. The span is denoted span(w1,...,wm) is the set of all linear combos of the w's

Every Span is a Linear Subspace - Let W = span(w1,...,wm). Then W is a linear subspace.

In [5]:
import numpy as np
x = np.array([[4, 5, 9]])
z = np.array([[1, 3, 5]])
print(np.cross(x, z))

[[ -2 -11   7]]


Column Space - Let A ∊ R^(nxm) be an nxm matrix with columns a1,...,am ∊ R^n. The column space of A, denoted col(A) is the span of the columns of A.

Linear Independence - A list of column vectors u1,...,um is linearly independent if none of them can be written as a linear combinations of the others.

Dimension Theorem - Let U be a linear subspace of V. Any basis of U has the same number of elements. All bases of U have the same length and same number of elements is dim(U).

A list of vectors {u1,...,um} is orthonormal if the u's are pairwise orthogonal and each has a norm 1 .

Orthogonal Projection - Let U ⊆ V be a linear subspace with orthonormal basis q1,...,qm. The orthogonal porjection of v ∊ V on U is Pu v = sum(j=1)< v , qj > qj.

Best Approximation Theorem - Let U ⊆ V be a linear subspace with orthonormal basis q1,...,qm let v ∊ V. For any u ∊ U. ||v-Pu v|| <= ||v-u||.

Pythagorean Theorem - Let u1 v ∊ V be orthogonal. Then ||u + v||^2 = ||u||^2 + ||v||^2

Cauchy-Schwarz - For any u1 v ∊ V , |<u,v>| <= ||u|| ||v||

Gram-Schmidt - Let a1,...,am in R^n be linearly independent. Then there exists an orthonormal basis, q1,...,qm of span(a1,...,am).

Eigenvalues and Eigenvectors - Let A ∊ R^(dxd) be a square matrix. Then 𝜆 ∊ R is an eigenvalue of A if there exists a non-zero vector x != 0 such that Ax = 𝜆x. Vector x is an eigenvector.

In [2]:
import numpy as np
from numpy.linalg import eig
x = np.array([ [5, 6], [3, 8] ])
w,v = eig(x)
print('E-value:', w)
print('E-vector', v)

E-value: [ 2. 11.]
E-vector [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


Diagonal and Similar Matrices - Let A be similar to a matrix D = diag(𝜆1,...,𝜆d) with distinct diagonal entries, that exists a non-singular matric A such that A = PDP^-1

If A is symmetric, then any 2 eigenvectors from different eigenspaces are orthogonal.

The Spectral Theorem of Symmetric Matrices - A nxn symmetric matrix A has the following properties:

A has n eigenvalyes, counting multiplicities.
If 𝜆 is an eigenvalues of A with multiplicity k, then the eigenspace for x is k-dimensional.
The eigenspaces are mutually orthogonal, in the sense that eigenvectrs corresponding to different vaues are orthogonal.
A is orthogonally diagonalizable.


# 1.3 - Least Squares Regression

QR Decomposition - a useful procedure to solve the linear least square problem using Gram-Schmidt.



In [9]:
import numpy as np
from numpy.linalg import qr
x = np.array([[1, 4], [8, 6]])

Q,R = qr(x)
print('Q:', Q)
print('R:', R)

z = np.dot(Q, R)
print('QR:', z)

iterations = [1, 30]
for i in range(30):
    Q,R = qr(x)
    x = np.dot(R, Q)
    if i+1 in iterations:
        print(f'Iteration {i+1}:')
        print(x)

Q: [[-0.12403473 -0.99227788]
 [-0.99227788  0.12403473]]
R: [[-8.06225775 -6.4498062 ]
 [ 0.         -3.2249031 ]]
QR: [[1. 4.]
 [8. 6.]]
Iteration 1:
[[ 7.4  7.2]
 [ 3.2 -0.4]]
Iteration 30:
[[ 9.68465844e+00 -4.00000000e+00]
 [ 3.03523277e-16 -2.68465844e+00]]


Normal Equations - Let A ∊ R^(nxm) be an nxm matrix with linearly independent columns and let b ∊ R^n be a vector. The solution to the least-squares problem min||Ax-b|| satisfies A^T Ax = A^T b which are known as the normal equations.

Least Squares via QR - Let A ∊ R^(nxm) be an nxm matrix with linearly independent column, let b ∊ R^n be a vector and let A = QR be a QR decomposition of A where Q is a R^(nxm) matrix with Q^T Q = I(mxm) and T is an upper triangle.